#Camera
USE_CAMERA_STUB:= false

#Platform
TARGET_BOARD_PLATFORM := msm7k
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
ARCH_ARM_HAVE_VFP := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv6-vfp
TARGET_CPU_ABI := armeabi
TARGET_CPU_ABI2 := armeabi-v6l
TARGET_BOOTLOADER_BOARD_NAME := swift
TARGET_OTA_ASSERT_DEVICE := swift
TARGET_GLOBAL_CFLAGS += -mfpu=vfp -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=vfp -mfloat-abi=softfp

#WiFi
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WPA_SUPPLICANT_VERSION := VER_0_5_X
BOARD_WLAN_DEVICE := bcm4325
BOARD_SOFTAP_DEVICE := bcm4325
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wireless.ko"
WIFI_DRIVER_MODULE_ARG := "firmware_path=/etc/wl/rtecdc.bin nvram_path=/etc/wl/nvram.txt config_path=/data/misc/wifi/config"
WIFI_DRIVER_MODULE_NAME := wireless
WIFI_DRIVER_FW_STA_PATH := "/system/etc/wl/rtecdc.bin"
WIFI_DRIVER_FW_AP_PATH := "/system/etc/wl/rtecdc-apsta.bin"
WIFI_DRIVER_HAS_LGE_SOFTAP := true
BOARD_WEXT_NO_COMBO_SCAN := true

#Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
WITH_A2DP := true
BOARD_CUSTOM_BRCM_PATCHRAM_PLUS := ../../../device/lge/swift/prebuilt/brcm_patchram_plus.c

#FM-Radio
BOARD_HAVE_FM_RADIO := true
BOARD_USE_BROADCOM_FM_VOLUME_HACK := true
BOARD_FM_DEVICE := bcm4325
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO

# Qcom
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
TARGET_PROVIDES_LIBRIL := true
TARGET_PROVIDES_INIT_TARGET_RC := true
BOARD_USE_NEW_LIBRIL_HTC := true

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := swift
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 1240

#Sensors
BOARD_VENDOR_USE_AKMD := true
BOARD_VENDOR_USE_AKMD := akm8973
TARGET_SENSORS_NO_OPEN_CHECK := true
TARGET_WANTS_OLD_ACTIVATE_BEHAVIOR := true

#Audio & Video
TARGET_PROVIDES_LIBAUDIO := true
BUILD_WITH_FULL_STAGEFRIGHT := true
TARGET_SF_NEEDS_REAL_DIMENSIONS := true

#Tweaks
WITH_DEXPREOPT := true
WITH_JIT := true
ENABLE_JSC_JIT := true
JS_ENGINE := v8
TARGET_WEBCORE_ENABLE_GIF := true
#WEBCORE_ACCELERATED_SCROLLING := true
#USE_DEFAULT_JS_ENGINE := true
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true
BOARD_NO_RGBX_8888 := true
BOARD_USE_NASTY_PTHREAD_CREATE_HACK := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true
TARGET_DO_NOT_SETS_CAN_DRAW := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_EGL_CFG := device/lge/swift/files/egl.cfg

#USB
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/usb_mass_storage/lun0/file"
BOARD_UMS_LUNFILE := "/sys/devices/platform/usb_mass_storage/lun0/file"

#System
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
BOARD_KERNEL_CMDLINE :=  mem=214M console=ttyMSM2,115200n8 androidboot.hardware=swift
BOARD_KERNEL_BASE := 0x00200000
BOARD_PAGE_SIZE := 0x00000800
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0f500000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x08a80000
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_PREBUILT_KERNEL := device/lge/swift/prebuilt/kernel/zImage
KERNEL_MODULES_DIR := /system/lib/modules

TARGET_SPECIFIC_HEADER_PATH := device/lge/swift/include

BOARD_GLOBAL_CFLAGS += -DCHARGERMODE_CMDLINE_NAME='"lge.reboot"'
BOARD_GLOBAL_CFLAGS += -DCHARGERMODE_CMDLINE_VALUE='"pwroff"'
